# Generated by Django 5.0.3 on 2024-05-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('name', models.CharField(blank=True, default='', help_text='This is for name', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=254)),
                ('paramater', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'General Settings',
                'verbose_name_plural': 'General Settings',
                'ordering': ('name', 'paramater'),
            },
        ),
        migrations.CreateModel(
            name='ImageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('name', models.CharField(blank=True, default='', help_text='This is for name', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=254)),
                ('file', models.ImageField(blank=True, default='', upload_to='media/img', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Image Settings',
                'verbose_name_plural': 'Image Settings',
                'ordering': ('file',),
            },
        ),
    ]
