# Generated by Django 5.0.3 on 2024-05-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('name', models.CharField(blank=True, default='', help_text='This is for name', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=254)),
                ('text', models.TextField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'about',
                'verbose_name_plural': 'about',
                'ordering': ('text',),
            },
        ),
    ]
