# Generated by Django 5.0.3 on 2024-05-21 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('order', models.ImageField(default=0, upload_to='', verbose_name='order')),
                ('name', models.CharField(blank=True, default=0, help_text='This is for name', max_length=100, verbose_name='Name')),
                ('percentage', models.ImageField(default=50, upload_to='', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percantage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
